### ISSUE TITLE
[BUG]   Webform.submit() incorrect work in version 4.13.1

### ISSUE THREAD

**Issue by AntonObleuhov** [formio/formio.js#4074]
### Environment
___

-  Hosting type
-  Form.io
-  Formio.js version: 4.13.1
-  Frontend framework: Angular
-  Browser: All
-  Browser version: All

When I use calling method submit() of instance Webform class then I get an error:
TypeError: this.submitForm(...).then(...).catch(...).finally is not a function
Can see https://github.com/formio/formio.js/blob/39bceb5750533ab3b32fe35b3be27a94ed98402d/src/Webform.js#L1530
Formio.js version: 4.13.0 work correctly!

**Comment by jalama** [comment]
I'm seeing this also.  Seems the issue is the [.finally method](https://github.com/formio/formio.js/blob/39bceb5750533ab3b32fe35b3be27a94ed98402d/src/Webform.js#L1536) is supported in es2018 and not es2015 (ie es6).  I tried setting my tsconfig.json to support the es2018 lib (ie target: "es2015", lib: ['dom", "es2018"]), following lead of  the [tsconfig](https://github.com/formio/angular/blob/master/projects/angular-formio/tsconfig.lib.json) in the @formio/angular project, to no avail.

As I understand it this would compile to es2015 and support "transpiling" support for es2018 features, but I may have this wrong.  I'm at a lose on this one and it's going to block us on updates pretty soon.

**Comment by ccontour** [comment]
https://www.typescriptlang.org/tsconfig#lib

It looks like ES2018 is the minimum to use the `.finally` on promises. You can try bringing in the ESNext lib instead to see if that resolves your situation. ES6/ES2015 should still be a good build target

**Comment by jalama** [comment]
This is fixed with 4.13.2, https://github.com/formio/formio.js/blob/v4.13.2/Changelog.md#4132-rc1
