### ISSUE TITLE
[BUG] Calendar widget has a focus issue

### ISSUE THREAD

**Issue by paulfalgout** [formio/formio.js#4523]
I'm having a hard time tracking down when this error is occurring or reproducing it, but I've been seeing it a lot since updating to 4.14.0 in our logs.

It's showing up as `o.focus is not a function`

And it's happening here:
https://github.com/formio/formio.js/blob/8baf5bfc2638101cfc349f7a5d9e8309538707db/src/components/_classes/component/Component.js#L3361

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
